# Copyright (c) 2016-2024 Makerdiary
#
# SPDX-License-Identifier: Apache-2.0

# Project information
site_name: Makerdiary Wiki
site_url: https://wiki.makerdiary.com
site_author: makerdiary
site_description: >-
  Learn how to develop with our featured products. Whether you're just getting started,
  or deep in the development process, our documentations make building easy and efficient.

# Repository
repo_name: github.com/makerdiary
repo_url: https://github.com/makerdiary
edit_uri: edit/main/docs/

# Copyright
copyright: 'Copyright &copy; 2016-2024 <a href="https://makerdiary.com" target="_blank">makerdiary</a>'

# Configuration
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  # Announcement bar
  announcement: ""

  # Home page
  home:
    hero:
      title: Welcome to Makerdiary Wiki
      description: >-
        Learn how to develop with all our products. Whether you're just getting started,
        or deep in the development process, our documentations make building easy and efficient.
      image: assets/images/home_hero.png
      button_primary:
        label: Get started
        link: products
      button_secondary:
        label: Shop now
        link: https://makerdiary.com/collections/all-products
    news:
      viewall: updates
      posts:
        - title: iMX RT1011 Nano Kit is Here!
          excerpt: >-
            We are excited to announce the iMX RT1011 Nano Kit, a small, high-performing prototyping kit designed
            around NXP iMX RT1011 Crossover MCU operating at up to 500 MHz.
          cover: updates/imx-rt1011-nano-kit-is-here/cover.png
          url: updates/imx-rt1011-nano-kit-is-here
          date: 2024-09-17
          readtime: 5
        - title: Documentation Updated for nRF52840 MDK USB Dongle
          excerpt: >-
            We are excited to announce that Documentation v2.0.0 is now available! There are many updates
            in this version that we hope you'll like.
          cover: updates/documentation-updated-for-nrf52840-mdk-usb-dongle/cover.png
          url: updates/documentation-updated-for-nrf52840-mdk-usb-dongle
          date: 2023-08-07
          readtime: 3
        - title: Introducing CircuitPython
          excerpt: >-
            CircuitPython is an implementation of Python for microcontrollers. Once you get your board set up,
            open any text editor, and start editing code.
          cover: updates/introducing-circuitpython/cover.png
          url: updates/introducing-circuitpython
          date: 2023-07-14
          readtime: 4
  collection_all:
    heading: Featured Products
    cards:
      - cover: assets/images/imxrt1011-nanokit-cover.png
        title: iMX RT1011 Nano Kit
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/imxrt1011-nanokit
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/imxrt1011-nanokit
      - cover: assets/images/nrf52840-connectkit-cover.png
        title: nRF52840 Connect Kit
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52840-connectkit
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52840-connectkit
      - cover: assets/images/m60plate-cover.png
        title: M60 Mechanical Keyboard Plate
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/m60
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/m60-mechanical-keyboard-plate
      - cover: assets/images/m60pcba-cover.png
        title: M60 Mechanical Keyboard PCBA
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/m60
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/m60-mechanical-keyboard-pcba
      - cover: assets/images/m2devkit-cover.png
        title: nRF52840 M.2 Developer Kit
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52840-m2-devkit/
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52840-m2-developer-kit
      - cover: assets/images/nrf52840-m2-module-cover.png
        title: nRF52840 M.2 Module
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52840-m2/
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52840-m2-module
      - cover: assets/images/pitayalink-cover.png
        title: Pitaya-Link CMSIS-DAP Debug Probe
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/pitaya-link
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/pitaya-link
      - cover: assets/images/pitaya-go-cover.png
        title: Pitaya Go nRF52840 WiFi IoT Board
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/pitaya-go
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/pitaya-go
      - cover: assets/images/mdkdongle-pcba-cover.png
        title: nRF52840 MDK USB Dongle (PCBA)
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52840-mdk-usb-dongle
      - cover: assets/images/ud52840wcase-cover.png
        title: nRF52840 MDK USB Dongle w/Case
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52840-mdk-usb-dongle-w-case
      - cover: assets/images/mdk52840-cover.png
        title: nRF52840-MDK IoT Development Kit
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52840-mdk
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52840-mdk-iot-development-kit
      - cover: assets/images/mdk52832v2-cover.png
        title: nRF52832-MDK V2 IoT Development Kit
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52832-mdk
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52832-mdk-v2-iot-development-kit
      - cover: assets/images/mdk52832-cover.png
        title: nRF52832-MDK IoT Development Kit
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/nrf52832-mdk
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/nrf52832-mdk-iot-micro-development-kit
      - cover: assets/images/base-dock-cover.png
        title: Base Dock (Grove Compatible)
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/base-dock
        button_secondary:
          label: Buy now
          link: https://makerdiary.com/products/base-dock
      - cover: assets/images/grove-mesh-kit-cover.png
        title: Grove Mesh Kit for nRF52840-MDK
        button_primary:
          label: Documentation
          link: https://wiki.makerdiary.com/grove-mesh-kit/
        button_secondary:
          label: Buy now
          link: https://www.seeedstudio.com/Grove-Mesh-Kit-for-nRF52840-MDK-p-4053.html

# Plugins
plugins:
  - search
  - blog:
      blog_dir: updates
      post_date_format: medium
      pagination_per_page: 6
      pagination_keep_content: true
      post_url_format: "{slug}"
      post_readtime_words_per_minute: 128
      categories: false
      archive: false
  # - git-revision-date-localized
  - minify:
      minify_html: true
  # TODO: Support Chinese
  # - i18n:
  #    default_language: en
  #    languages:
  #      en: English
  #      zh: 简体中文

# Customization
extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/shopify
      link: https://makerdiary.com
    - icon: fontawesome/brands/github
      link: https://github.com/makerdiary
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/makerdiary
    - icon: fontawesome/brands/discourse
      link: https://community.makerdiary.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@makerdiary
    - icon: fontawesome/solid/blog
      link: https://blog.makerdiary.com
    - icon: fontawesome/brands/medium
      link: https://medium.com/makerdiary
    - icon: fontawesome/solid/envelope
      link: mailto:hi@makerdiary.com

extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: makerdiary
      repo: imxrt1011-nanokit
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Products:
    - products/index.md
  - Updates: updates/index.md
  - Discussions: https://github.com/orgs/makerdiary/discussions
